import './globals.css'
import Link from 'next/link'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header>
          <nav>
            <Link href='/'>devjobs</Link>
          </nav>
        </header>
        <main>
        {children}
        </main>
      </body>
    </html>
  )
}
